### ISSUE TITLE
Local group membership issue

### ISSUE THREAD

**Issue by Wikh** [SenseNet/sn-workspaces#3] opened 2017-07-27 09:38 UTC
I have a workspace template with local groups referencing to each other. When creating a new workspace based on this template the group membership references under the new instance are not updated - so they still refer to the groups under the template.

**Comment by Wikh** [comment] 2017-07-27 09:46
![template](https://user-images.githubusercontent.com/7532838/28664573-30b52ca8-72c1-11e7-8809-1ea03279e42f.png)

**Comment by tusmester** [comment] 2017-07-29 17:55
We have to check the *ContentTemplate* class (in the *Services* component, *ContentRepository* project), most likely the *UpdateLocalReferences* method.

**Comment by borsi** [comment] 2017-09-06 08:08
Waiting for Joe to confirm it works as intended

**Comment by VargaJoe** [comment] 2017-09-20 07:36
Confirmed.

**Comment by tusmester** [comment] 2017-09-20 07:43
(it was fixed by [this PR](https://github.com/SenseNet/sensenet/pull/136))

**Closed** 2017-09-20 08:10 UTC
Labels: bug, KFI
